### ISSUE TITLE
Can i select multiple items and drang at time?

### ISSUE THREAD

**Issue by SivaPrakashK90** [ObaidUrRehman/ng-drag-drop#125]
Hi ObaidUrRehman,
I have two list items I'm Dragging the item from one list and adding it to the other list by dropping the item
till now everything is working fine. Is it possible to add multiple items at a time by using drag and drop? if yes what is the process?

**Comment by ObaidUrRehman** [comment]
@SivaPrakashK90 I am afraid this is not possible with this component.
