### ISSUE TITLE
Basic example doesn't work, dropping item does nothing.

### ISSUE THREAD

**Issue by egozavr** [ObaidUrRehman/ng-drag-drop#127]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] other

* **What is the current behavior?**
Basic example from manual doesn't work for me. When I drop item nothing happens. May be its's not compatible with stackblitz.
Code is [here](https://stackblitz.com/edit/angular-drag-drop-example).

**Comment by ObaidUrRehman** [comment]
The basic requirement is to have an onDrop handler on the `droppable` & set drag data on the `draggable`.
I modified your example to include both. Link: https://stackblitz.com/edit/angular-drag-drop-example-tw7dt3

**Comment by egozavr** [comment]
Thanks, it's clear now )
