### ISSUE TITLE
Is it possible to get the target element ?

### ISSUE THREAD

**Issue by SkYNewZ** [ObaidUrRehman/ng-drag-drop#139]
[ ] bug report
[x] feature request
[x] other

Hi!

I currently start using this library with a multiple element that are draggable & droppable each other.
I can have the draged element with the `onDrop` event but I need to have the target element on which it's deposited, is it possible ?

**Comment by redevill** [comment]
Or, in the case of multiple elements inside a single container, to be able to define a "target" in this case. Because you would need to know where, in the container you are dropping your item. This would allow a sorting use case.

**Comment by JBrownie77** [comment]
I got it to work this way:
(onDrop)="onDrop($event, <target or other data>)"

public onDrop(e: any, target: any): void {
}
