### ISSUE TITLE
rxjs_1.of is not a function

### ISSUE THREAD

**Issue by jitendramalan7** [ObaidUrRehman/ng-drag-drop#140]
When I am dropign an element is showing an error in console like rxjs_1.of is not a function. Please provide the solution for this. it will be a great help.

Thanks in advanced.

![image](https://user-images.githubusercontent.com/18457124/41819672-12f0afae-77e2-11e8-9062-829bb05f95f4.png)

**Comment by jitendra-tft** [comment]
facing the same issue

**Comment by jitendra-tft** [comment]
using rxjs version 5.5.11 and ng-drag-drop version latest

**Comment by thimovss** [comment]
Same problem here, any known work around available?

**Comment by ObaidUrRehman** [comment]
what version of angular?

**Comment by jitendra-tft** [comment]
5

**Comment by ObaidUrRehman** [comment]
This component was upgraded to use angular v6 & rxjs v6.1.0. I think you will need to fall back to the one previous version.

**Comment by jitendramalan7** [comment]
Thank you. I just move to back version and it is working fine.

**Comment by joesleiman** [comment]
i have the same issue:
angular: 5
how should i downgrade angular to old version (4) and u said that the component was upgraded to use angular 6 , it;s not logical, as i understand.
and in this link https://www.npmjs.com/package/ng-drag-drop#installation 
documentation of ng-drag-drop they said that it's for angular 5 not 6 .

**Comment by JBrownie77** [comment]
+1. Which version for angular 5?

**Comment by scotch83** [comment]
Hello, sorry but I see in this repo only versions until the 4.0.1, while the npm package I download is already at 5.
Did this get somehow replaced by something else?
