### ISSUE TITLE
Creating image when start deragging

### ISSUE THREAD

**Issue by TKul6** [ObaidUrRehman/ng-drag-drop#151]
Please remove sections that are not required.

* **I'm submitting a ...**
[ ] bug report
[X ] feature request
[ ] other

* **What is the current behavior?**

The **onDragStart** event is invoked after the image has been added to the dataTransfer object of the drag event.

In my site, I wish to create a specific image depended on the user's current object drop.

I tried to hook to the **onDragStart** and change the image Url, unfortunately it is too late, and the image is displayed only at the second drag. 

* **What is the expected behavior?**
If there was an event that is invoked right before you start all the drag calculation, Maybe I could create the image there, and the bind will work.
Alternatively, maybe I can provide a lambda that creates an image uri instead of the dragImage property?

I'm in a real mess and not sure what to do.

Can you please help me?

* **Please tell us about your environment:**
Angular CLI: 6.0.7
Node: 9.0.0
OS: win32 x64
Angular: 6.0.4
... compiler, core

Package Version
@angular-devkit/architect 0.6.7 (cli-only)
@angular-devkit/core 0.6.7 (cli-only)
@angular-devkit/schematics 0.6.7 (cli-only)
@schematics/angular 0.6.7 (cli-only)
@schematics/update 0.6.7 (cli-only)
rxjs 6.2.0
typescript 2.7.2

Thanks

**Comment by uareurapid** [comment]
hi @TKul6 
I don't think any of these will get fixed, the project maintainer announced the end of it: https://github.com/ObaidUrRehman/ng-drag-drop

**Comment by TKul6** [comment]
Moved to Material CDK Drag & Drop
